### ISSUE TITLE
Is there an ETA on Code publication?

### ISSUE THREAD

**Issue by hasanhaja** [ifnspaml/CIL_Segmentation#1]
Hi! I found your paper "Class-Incremental Learning for Semantic Segmentation Re-Using Neither Old Data Nor Old Labels" really interesting and I was wondering if you had an ETA on when the code might be published?

**Comment by klingner** [comment]
Sorry for responding that late! The preparation of the code is basically finished and we intend to publish it within the next 3 weeks.
