### ISSUE TITLE
dataset_index.py

### ISSUE THREAD

**Issue by ljx97** [ifnspaml/CIL_Segmentation#2]
Hi,I can't find dataset_index.py in the folder dataloader/file_io. Where is dataset_index.py?Thanks a lot for your answer.

**Comment by klingner** [comment]
Hi, for what purpose do you need the file for? The code should be executable without it actually. 
If you should indeed need it, you can find it in the dataloader repository on github: https://github.com/ifnspaml/IFN_Dataloader.
