### ISSUE TITLE
datasets

### ISSUE THREAD

**Issue by LifeIsBright-heihei** [ifnspaml/CIL_Segmentation#4]
Hi,if i want to change the number of train image,how can i do that,i try to change json files,but it's useless

**Comment by klingner** [comment]
Hi, could you maybe describe a little bit more specific what your intention is? Do you want to add data from outside the Cityscapes dataset? Add more data inside the Cityscapes dataset? Without further information, i am afraid that I cannot answer your question properly.

**Comment by LifeIsBright-heihei** [comment]
Hi,I want to add add more data inside the Cityscapes dataset or reduce some data from the Cityscapes dataset,I want to see what different result about them.

**Comment by klingner** [comment]
Hi, inthat case I think you should have a look at the file ``src/city_set.py`` in which the cities from which the data should be taken are defined for the single stages. 

If you want to add data from outside the usual 2975 cityscapes image, I think you need to define a new dataset (maybe with the help of our dataloader github repository) and then use the pytorch ``ConcatDataset`` class to combine them.

**Comment by LifeIsBright-heihei** [comment]
thank you for your help
